
SELECT	i.ID,
		i.INVOICENO, 
		i.ACCOUNTID, 
		MAX(i.CREATEDATETIME) AS CREATEDATETIME,
		MAX(i.TOTAL) AS TOTAL,
		SUM(D.AMOUNT) AS AMOUNT,
		MAX(i.STATUS) AS STATUS
FROM INVOICE I
	LEFT JOIN INVOICEDETAIL D
		ON i.ID = D.INVOICEID
WHERE i.ACCOUNTID=/*accountId*/
	AND i.STATUS=1
GROUP BY i.ID
ORDER BY i.CREATEDATETIME, i.TOTAL, i.INVOICENO, i.ACCOUNTID