
CREATE TABLE CATEGORY(
	ID SERIAL PRIMARY KEY,
	CODE CHARACTER VARYING(3) NOT NULL UNIQUE,
	NAME CHARACTER VARYING(120),
	STATUS INTEGER DEFAULT 1
	 
);

CREATE TABLE BOOK(
	ID SERIAL PRIMARY KEY,
	CODE CHARACTER VARYING(10) NOT NULL,
	TITLE CHARACTER VARYING(120) NOT NULL,
	CATEGORYID INTEGER,
	AUTHOR CHARACTER VARYING(120),
	AMOUNT NUMERIC(10,0) NOT NULL,
	IMPORTDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRICE NUMERIC(5,0) NOT NULL,
	UPDATEDATETIME TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
	STATUS INTEGER DEFAULT 1
);


CREATE TABLE ROLE(
	ID SERIAL PRIMARY KEY,
	NAME CHARACTER VARYING(120),
	STATUS INTEGER DEFAULT 1
);

CREATE TABLE ACCOUNT(
	ID SERIAL PRIMARY KEY,
	NAME CHARACTER VARYING(120) NOT NULL,
	CODE CHARACTER VARYING(10) NOT NULL,
	PASSWORD CHARACTER VARYING(50) NOT NULL,
	ADDRESS CHARACTER VARYING(120) NOT NULL,
	EMAIL CHARACTER VARYING(120) NOT NULL,
	STATUS INTEGER DEFAULT 1,
	ROLEID INTEGER
);

CREATE TABLE INVOICE(
	ID SERIAL PRIMARY KEY,
	INVOICENO CHARACTER VARYING(10) NOT NULL,
	ACCOUNTID INTEGER,
	CREATEDATETIME TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	TOTAL NUMERIC(13,0),
	STATUS INTEGER DEFAULT 1 NOT NULL
);

CREATE TABLE INVOICEDETAIL(
	ID SERIAL PRIMARY KEY,
	INVOICEID INTEGER,
	BOOKID INTEGER,
	AMOUNT NUMERIC(5,0),
	PRICE NUMERIC (5,0)
);

-- CREATE FOREIGN KEY

ALTER TABLE INVOICEDETAIL ADD CONSTRAINT FK_INVOICEDETAIL_INVOICE FOREIGN KEY(INVOICEID) REFERENCES INVOICE(ID);
ALTER TABLE INVOICEDETAIL ADD CONSTRAINT FK_INVOICEDETAIL_BOOK FOREIGN KEY(BOOKID) REFERENCES BOOK(ID);

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_ROLE FOREIGN KEY(ROLEID) REFERENCES ROLE(ID);


ALTER TABLE BOOK ADD CONSTRAINT FK_BOOK_CATEGORY FOREIGN KEY(CATEGORYID) REFERENCES CATEGORY(ID);

-- INSER VALUE
INSERT INTO CATEGORY(CODE,NAME) VALUES('stn', 'Sách Thiếu Nhi');
INSERT INTO CATEGORY(CODE,NAME) VALUES('skt', 'Sách kinh tế');
INSERT INTO CATEGORY(CODE,NAME) VALUES('snn', 'Sách Ngoại Ngữ');
INSERT INTO CATEGORY(CODE,NAME) VALUES('scn', 'Sách Công Nghệ');


INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000003','SACH TN 03',1,'Tac gia 1',11,CURRENT_TIMESTAMP,20000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000004','SACH TN 04',1,'Tac gia 1',12,CURRENT_TIMESTAMP,20000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000005','SACH TN 05',1,'Tac gia 1',13,CURRENT_TIMESTAMP,20000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000006','SACH TN 06',1,'Tac gia 1',14,CURRENT_TIMESTAMP,20000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000007','SACH TN 07',1,'Tac gia 2',15,CURRENT_TIMESTAMP,20000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000008','SACH TN 08',1,'Tac gia 3',16,CURRENT_TIMESTAMP,20000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000009','SACH TN 09',1,'Tac gia 4',17,CURRENT_TIMESTAMP,30000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000010','SACH TN 10',1,'Tac gia 5',18,CURRENT_TIMESTAMP,30000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000011','SACH TN 11',1,'Tac gia 6',19,CURRENT_TIMESTAMP,30000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000012','SACH TN 12',1,'Tac gia 7',20,CURRENT_TIMESTAMP,30000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000013','SACH TN 13',1,'Tac gia 8',21,CURRENT_TIMESTAMP,30000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000014','SACH TN 14',1,'Tac gia 9',22,CURRENT_TIMESTAMP,30000,CURRENT_TIMESTAMP);
INSERT INTO BOOK(CODE, TITLE, CATEGORYID, AUTHOR, AMOUNT, IMPORTDATE, PRICE, UPDATEDATETIME)  VALUES('STN0000015','SACH TN 15',1,'Tac gia 10',23,CURRENT_TIMESTAMP,30000,CURRENT_TIMESTAMP);

INSERT INTO ROLE(NAME) VALUES('Admin');
INSERT INTO ROLE(NAME) VALUES('Customer');


INSERT INTO ACCOUNT(NAME, CODE, PASSWORD, ADDRESS, EMAIL, ROLEID) VALUES('Admin, 'CUS0000001','1','dia chi','a@gmail.com',2);

-- Insert invoice
-- drop function insertInvoice( integer,  integer)
CREATE OR REPLACE FUNCTION insertInvoice(in_accountId in integer, in_total  in integer)
RETURNS integer AS $$
DECLARE id integer;

          BEGIN
            INSERT INTO invoice(invoiceno, accountId, createdatetime, total)
            VALUES('0001',in_accountId,CURRENT_TIMESTAMP,in_total);
            SELECT LASTVAL() into id;
            return id; 
          END;
 
     $$ LANGUAGE 'plpgsql'